server:
  port: 8081

spring:
  web:
    resources:
      static-locations: classpath:/static/
  datasource:
    url: jdbc:mysql://${MYSQL_HOSTNAME}:${MYSQL_PORT}/${MYSQL_DATABASE_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      #Quanto l'applicazione parte interagisce con il database. ddl-auto values:
      # create-drop -> creazione del db all'avvio e distruzione alla chiusura dell'applicazione
      #update -> aggiorna il db con le tabelle nuove, modifica quelle attuali, non elimina le eventuali colonne che non esistono più
      #Le tabelle vengono aggiornate in base ai valori delle classi
      #validated -> confronta le entità con le tabelle e solleva eccezioni se ci sono incongruenze
      #none: non viene fatto nulla (da usare assolutamente in produzione per non toccare la struttura del database)
      ddl-auto: update
    properties:
      #Per generare delle query ottimizzate sul tipo di databse che si utilizza
      dialect: org.hibernate.dialect.MySQLDialect
      hibernate:
        #Per formattare con l'indentazione le query sql nel file di log
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
    show-sql: true
    open-in-view: false
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
logging:
  level:
    com.example.ToDo: info
    prg.hibernate.orm.jdbc.bind: trace #Nel log riesco a vedere il tipo di parametri che passo nelle query
    org.springframework.security: debug
